# Generated by Django 3.0.6 on 2020-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IP地址')),
                ('STATE', models.CharField(choices=[('down', '设备已关机'), ('up', '设备开机'), ('avi', '此IP未分配')], max_length=30, verbose_name='当前状态')),
                ('MODEL', models.CharField(blank=True, choices=[('fwq', '普通服务器'), ('gmszx', '高密四子星'), ('ups', 'UPS'), ('ccjd', '存储节点'), ('others', '其他')], max_length=30, verbose_name='型号')),
                ('IDD', models.CharField(blank=True, max_length=30, verbose_name='设备编号')),
                ('USER', models.CharField(blank=True, max_length=30, verbose_name='设备使用者')),
                ('TEL', models.CharField(blank=True, max_length=30, verbose_name='联系方式')),
                ('LOC', models.CharField(blank=True, max_length=30, verbose_name='设备位置')),
                ('NOTE', models.CharField(blank=True, max_length=30, verbose_name='备注')),
                ('TIME', models.DateTimeField(auto_now_add=True)),
                ('IPMI', models.CharField(blank=True, help_text='Example:172.25.0.0', max_length=30, unique=True, verbose_name='IPMI地址')),
            ],
            options={
                'verbose_name': 'IP',
                'verbose_name_plural': 'IP查询',
            },
        ),
    ]
