# Generated by Django 3.0.6 on 2020-05-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DR', '0002_auto_20200524_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'managed': False, 'verbose_name': '病例信息', 'verbose_name_plural': '病例信息'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False, 'verbose_name': '病人信息', 'verbose_name_plural': '病人信息'},
        ),
    ]
