# Generated by Django 3.0.6 on 2020-05-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DR', '0003_auto_20200525_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DrPublisher',
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False},
        ),
    ]
