# Generated by Django 3.0.6 on 2020-06-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DR', '0004_auto_20200526_1106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'managed': False, 'verbose_name_plural': '病例管理'},
        ),
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'managed': False, 'verbose_name_plural': '诊断管理'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'managed': False, 'verbose_name_plural': '病人管理'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': False, 'verbose_name_plural': '照片管理'},
        ),
    ]
