# Generated by Django 3.0.6 on 2020-06-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DR', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
