# Generated by Django 3.0.6 on 2020-06-04 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DR', '0007_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'managed': False, 'verbose_name_plural': '诊断信息'},
        ),
    ]
